# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "zenergy" "nct6775" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.zenergy
    (config.boot.kernelPackages.callPackage ./r8127.nix {})
    (config.boot.kernelPackages.callPackage ./keychron-battery.nix {})
  ];
  hardware.i2c.enable = true;
  boot.blacklistedKernelModules = [ "r8169" ];
  boot.kernelParams = [
    "amd_pstate=on"
    "amdgpu.ppfeaturemask=0xffffffff" # AMD GPU Overclocking unlock
    "mitigations=off"
    "threadirqs"
    "preempt=full"
    # "mem_sleep_default=s2idle"
    # "transparent_hugepage=never"
    # "pcie_aspm=off"
    "amdgpu.aspm=0"
    # "isolcpus=managed_irq,1"
    # "nohz_full=1"
    # "rcu_nocbs=1"
    # "irqaffinity=0,2-7"
  ];

  # boot.kernelPatches = [{
  #   name = "realtime";
  #   patch = null;
  #   structuredExtraConfig = with lib.kernel; {
  #     EXPERT = yes;
  #     PREEMPT_RT = yes;

  #     PREEMPT = lib.mkForce yes;
  #     # Fix error: error: unused option: PREEMPT_VOLUNTARY
  #     PREEMPT_VOLUNTARY = lib.mkForce unset;

  #     DRM_I915_GVT = lib.mkForce unset;
  #     DRM_I915_GVT_KVMGT = lib.mkForce unset;

  #     IRQSOFF_TRACER = yes;
  #     PREEMPT_TRACER = yes;
  #     HWLAT_TRACER = yes;
  #     OSNOISE_TRACER = yes;
  #     TIMERLAT_TRACER = yes;
  #   };
  # }];

  boot.kernelPatches = [{
    name = "realtime";
    patch = null;
    structuredExtraConfig = with lib.kernel; {
      # HZ = freeform "1000";
      # HZ_1000 = yes;
      # HZ_250 = lib.mkForce unset;

      IRQSOFF_TRACER = yes;
      PREEMPT_TRACER = yes;
      HWLAT_TRACER = yes;
      OSNOISE_TRACER = yes;
      TIMERLAT_TRACER = yes;
    };
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  environment.systemPackages = with pkgs; [ amdgpu_top ];
}
